### ISSUE TITLE
Recreate Elon's Musk The Boring Company website

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#1]
Help recreate a simple white background website.

Issues requested:

1. Add a white background
2. Center images and videos
3. Add the links and pictures found in the folder provided to submit your pull request.
![Files to submit your pull request](https://user-images.githubusercontent.com/22683645/46261478-fe715900-c4eb-11e8-819d-2a4f1149529a.PNG)

**Comment by adlyloukil** [comment]
Layout to be replicated ![Reference Layout](https://user-images.githubusercontent.com/22683645/46261582-6d02e680-c4ed-11e8-8203-13bd1533664f.jpg)

**Comment by mx0c** [comment]
Hey, i'd like to help you with this issue. Do you want plain html and css or can i use bootstrap etc..?

**Comment by adlyloukil** [comment]
@mx0c You can use bootstrap or anything which helps you recreate it. Looking forward to seeing you help with this issue!

**Comment by iamsubhro** [comment]
Hey, I cam help you with this..

**Comment by adlyloukil** [comment]
@iamsubhro would appreciate if you could give @mx0c some time to submit his pull request then you can contribute to his pull request!

**Comment by iamsubhro** [comment]
Yes absolutely

**Comment by itsVagabond** [comment]
I have made my first pull request. Please look to it and give me the feedback.

**Comment by mx0c** [comment]
@itsVagabond next Time look into the issues if someone is already working on it. #3

**Comment by adlyloukil** [comment]
@mx0c Thank you for your contribution! I have merged your pull request. @iamsubhro feel free to contribute further! @itsVagabond Thank you for your first pull request however I have merged @mx0c pull request instead. You are more then welcome to contribute now if you see some improvements you would like to make.

Thank you all for your contributions thus far.

**Comment by itsVagabond** [comment]
@mx0c  I have seen the comment section after I have requested the pull. 
I will keep that in mind.
