### ISSUE TITLE
Add a unique Favicon to the website! 

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#26]
Create a favicon and add it to the website

**Comment by kev1nboer** [comment]
Can I do this @adlyloukil?

**Comment by msaoudallah** [comment]
@adlyloukil  you don't have any specs for the icon ?

**Comment by adlyloukil** [comment]
@msaoudallah Black and white but unique perhaps put a square inside a circle the opposite of the boring companies if that makes sense. Also can you put the .PSD file into the files folder.

**Comment by msaoudallah** [comment]
@adlyloukil  actually i started working before seeing your reply, and made a pull request #29  , i made it a black square.

**Comment by syauqiahmd** [comment]
may i contribute on this ?

**Comment by adlyloukil** [comment]
Thanks to everyone who contributed!
