### ISSUE TITLE
Fix the spacing issue at the bottom of this respositories website!

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#27]
Fix the white spacing and all spacing issues with the website. Use www.theboringcompany.com as a reference website.

**Comment by 8ivek** [comment]
@adlyloukil : giving me 404 error

**Comment by adlyloukil** [comment]
@8ivek what is?

**Comment by 8ivek** [comment]
@adlyloukil its fine now the url is working

**Comment by homard** [comment]
you mean : https://www.boringcompany.com/

**Comment by adlyloukil** [comment]
Thank you to all contributors!
