### ISSUE TITLE
Make the website more responsive for mobile and tablets

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#28]
^^

**Comment by kev1nboer** [comment]
@adlyloukil I can scale down the logo a bit? I think this would help. I can also update the navigation so that it's easier to see on small displays?

**Comment by adlyloukil** [comment]
@kev1nboer as you wish

**Comment by kev1nboer** [comment]
@adlyloukil see #30 for my pull request!

**Comment by adlyloukil** [comment]
Thanks everyone for your contributions!
