### ISSUE TITLE
Code the buttons to take you to other pages

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#45]
1. Allow the Home button to take you to the home page.
- The FAQ page to take you to another webpage
- etc etc 

2. Populate the web pages with Lorem ipsum text

![Buttons](https://user-images.githubusercontent.com/22683645/46557667-956e5480-c8e2-11e8-967e-f4d6596f1dd3.PNG)

**Comment by kosijer** [comment]
I'm taking this one

**Comment by kosijer** [comment]
All done
