### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#5]
The current website has spacing issues, please correct the spacing to match www.theboringcompany.com

**Comment by adlyloukil** [comment]
@Quantumf0x by website I mean this repository! Please correct the spacing like www.theboringcompany.com

**Comment by emilycolon** [comment]
If this issue is still available, I'd like to tackle it.  Thanks!

**Comment by cdeepanshu** [comment]
can you plz tell me what type of spacing issue is present on the website so that I can help you with this issue.

**Comment by dalvia62** [comment]
Headder Spacing issue solve 

added to the style sheet 
    margin: 0 auto;
   and also decrease padding: 80px; to padding: 40px;

Now its look like the boring company 
and also added <br/> after menu end so the spacing issue of header solve

**Comment by Quantumf0x** [comment]
Modify:
- menu css #linknav
- iframe css on mobile 

Delete:
Col around menu

**Comment by adlyloukil** [comment]
Thank you for your all your help guys
