### ISSUE TITLE
Create a Simple but different banner like Elon Musks the BoringCompany!

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Lets-Build-a-website-together#7]
Create a simple .PNG translucent banner with the same dimensions as theboringcompany's banner found below:

![theboringcompany logo](https://user-images.githubusercontent.com/22683645/46299273-e9063880-c598-11e8-803f-757411030426.png)

Dimensions : 1080x453

**Comment by gayankalhara** [comment]
Working on it...

**Comment by adlyloukil** [comment]
@gayankalhara Great!

**Comment by adlyloukil** [comment]
@gayankalhara if you could change it to "The Sealing Company and include the .PSD file that would be great (if you are using photoshop)

**Comment by yugenchokshi** [comment]
I'll make it happen

**Comment by yugenchokshi** [comment]
How do I PR for image?
@adlyloukil

**Comment by adlyloukil** [comment]
@yugenchokshi Looking forward to seeing it!

**Comment by yugenchokshi** [comment]
@adlyloukil You can close it! I pushed it already ;)
